agnevo/agnevo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from realty.views import SearchView, SubmitView, RealtyView, SubmitSuccessView, SubscribeView, \
    SubscribeDeleteView, RealtyFavouriteView, RevelationView, UserView, UserRealtyDeleteView, UserRealtyShowView, \
    UserRealtyHideView, UserRealtyFavouriteView
from accounts.views import LoginView, LogoutView, RegisterView, ResendView, \
    PayView, PayRobokassaSuccessView, PayRobokassaFailView, \
    PayRobokassaResultView, FeedbackView, FeedbackThanksView, AgreementView, OfferView, DiscountView


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AgNeVo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', SearchView.as_view(), name='search'),
    url(r'^submit/$', SubmitView.as_view(), name='submit'),
    url(r'^submit/success/$', SubmitSuccessView.as_view(), name='submit_success'),
    url(r'^realty/(?P<id>\d+)/$', RealtyView.as_view(), name='realty'),
    url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
    url(r'^feedback/thanks/$', FeedbackThanksView.as_view(), name='feedback_thanks'),
    url(r'^subscribe/$', SubscribeView.as_view(), name='subscribe'),
    url(r'^favourite/$', RealtyFavouriteView.as_view(), name='favourite'),
    url(r'^subscribe/delete/$', SubscribeDeleteView.as_view(), name='subscribe_delete'),
    url(r'^agreement/$', AgreementView.as_view(), name='agreement'),
    url(r'^offer/$', OfferView.as_view(), name='offer'),
    url(r'^discount/$', DiscountView.as_view(), name='discount'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^account/login/$', LoginView.as_view(), name='login'),
    url(r'^account/log_out/$', LogoutView.as_view(), name='logout'),
    url(r'^account/register/$', RegisterView.as_view(), name='register'),
    url(r'^account/resend/$', ResendView.as_view(), name='resend'),
    url(r'^account/revelation/$', RevelationView.as_view(), name='revelation'),
    url(r'^account/pay/$', PayView.as_view(), name='pay'),
    url(r'^account/pay/robokassa/success/$', PayRobokassaSuccessView.as_view(), name='pay_robokassa_success'),
    url(r'^account/pay/robokassa/fail/$', PayRobokassaFailView.as_view(), name='pay_robokassa_fail'),
    url(r'^account/pay/robokassa/result/$', csrf_exempt(PayRobokassaResultView.as_view()), name='pay_robokassa_result'),
    url(r'^account/user/$', UserView.as_view(), name='user'),
    url(r'^account/user/realty/(?P<pk>\d+)/delete/$', UserRealtyDeleteView.as_view(), name='user_realty_delete'),
    url(r'^account/user/realty/(?P<pk>\d+)/show/$', UserRealtyShowView.as_view(), name='user_realty_show'),
    url(r'^account/user/realty/(?P<pk>\d+)/hide/$', UserRealtyHideView.as_view(), name='user_realty_hide'),
    url(r'^account/user/realty/(?P<pk>\d+)/favourite/$', UserRealtyFavouriteView.as_view(), name='user_realty_favourite'),


    url(r'^api/account/login/$', csrf_exempt(LoginView.as_view())),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agnevo/accounts/forms.py
# -*- coding: utf-8 -*-
import re
from django import forms
from captcha.fields import CaptchaField


class AccountForm(forms.Form):
    def set_error(self, field, msg):
        self._errors[field] = self.error_class([msg])

    def clean_login(self):
        data = self.cleaned_data['login']
        if not re.match(r'^\d{10}$', data):
            raise forms.ValidationError('Неверный номер телефона')
        return data


class AuthenticationForm(AccountForm):
    login = forms.CharField(label="Phone", max_length=10,
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Телефон'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))


class RegistrationForm(AccountForm):
    login = forms.CharField(label="Phone", max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField()


class ResendForm(AccountForm):
    login = forms.CharField(label="Phone", max_length=10)
    captcha = CaptchaField()


class FeedbackForm(AccountForm):
    name = forms.CharField(label="Name", max_length=255, required=False,
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ваше имя'}))
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'текст сообщения', 'rows': '3'}))

agnevo/common/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="Снимайте или сдавайте жилье без посредников. Все объявления в нашей базе проверены оператором. Экономьте на агентской комиссии и решайте жилищный вопрос быстро и надежно!"/>
    <title>Агнево - Недвижимость от собственников</title>
    <link rel="shortcut icon" type="image/ico" href="/static/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">

    {% block link %}{% endblock %}

    <script language='javascript'>
        function SubmitForm(form_id) {
           var form=document.getElementById(form_id);
           form.submit();
        }
    </script>
    <style>
        body { padding-top: 60px; }
        .jumbotron { padding-top: 10px; padding-bottom: 10px; margin-bottom: 10px; background-color: #fff; }
        .jumbotron p { font-size: 16px; font-weight: 200; margin-bottom: 3px; }
    </style>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/" style="color: #dddddd;">
                    <nobr><span class="glyphicon glyphicon-home" style="margin-right: 5px;"></span>Агнево - Недвижимость от собственников</nobr>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <div class="navbar-right">
                    <div class="btn-group">
                        <a type="button" class="btn navbar-btn btn-default" href="{% url 'user' %}">+7{{ user.login }}</a>
                        {% if user.is_premium %}
                        <a type="button" class="btn navbar-btn btn-success" href="{% url 'user' %}">Премиум истекает {{ user.premium_to|date:"d-m-Y H:i" }}</a>
                        {% else %}
                        <a type="button" class="btn navbar-btn btn-default" href="/">Баллы: {{ user.points }}</a>
                        <a type="button" class="btn navbar-btn btn-success" href="{% url 'pay' %}">Активировать премиум</a>
                        {% endif %}
                    </div>
                    <a type="button" class="btn navbar-btn btn-primary" href="{% url 'logout' %}">Выйти</a>
                </div>
                {% else %}
                <form method="post" action="{% url 'login' %}" class="navbar-form navbar-right" role="form">
                    {% csrf_token %}
                    <div class="input-group">
                        <span class="input-group-addon">+7</span>
                        <input id="id_login" maxlength="10" name="login" type="text" placeholder="Телефон" class="form-control">
                    </div>
                    <div class="form-group">
                        <input id="id_password" name="password" type="password" placeholder="Пароль" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">Вход</button>
                    <a type="button" class="btn btn-primary" href="{% url 'register' %}">Регистрация</a>
                </form>
                {% endif %}
            </div>
        </div>
    </div>

    {% block page %}
    {% if True %}
    <div class="jumbotron">
        <div class="container-fluid">
            <div class="col-md-3">
                <img src="{{ STATIC_URL }}images/logo_site_159x120.png">
            </div>
            <div class="col-md-9">
                <br>
                <p>Снимайте или сдавайте жилье без посредников. Все объявления в нашей базе проверены оператором. Экономьте на агентской комиссии и решайте жилищный вопрос быстро и надежно!</p>
                <br>
                <p>Есть вопросы? Задайте их прямо сейчас!</p>
                <p>Телефон: +7-937-089-55-00</p>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="container">
        <ul class="nav nav-tabs">
            <li class="{{ menu_selected.search }}"><a href="{% url 'search' %}">Поиск</a></li>
            <li class="{{ menu_selected.submit }}"><a href="{% url 'submit' %}">Сдать</a></li>
        {% if False %}
            <li class="{{ menu_selected.about }}"><a href="{% url 'about' %}">О нас</a></li>
        {% endif %}
            <li class="{{ menu_selected.feedback }}"><a href="{% url 'feedback' %}">О проекте</a></li>
            <li class="{{ menu_selected.pay }}"><a href="{% url 'pay' %}">Оплата</a></li>
            <li class="{{ menu_selected.subscribe }}"><a href="{% url 'subscribe' %}">СМС подписка</a></li>
            {% if user.is_authenticated %}
            <li class="{{ menu_selected.user }}"><a href="{% url 'user' %}">Мои объявления</a></li>
            {% endif %}
            {% if is_discount %}
            <li class="{{ menu_selected.discount }}">
                <a href="{% url 'discount' %}" style="color: #DD0000;">Акция</a>
            </li>
            {% endif %}
        </ul>
        <br>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
            {% block content %}{% endblock %}
            </div>
        </div>

        {% block custom_content %}{% endblock %}

    </div>
    {% endblock %}

    <div class="container">
        <p style="text-align: center;"> © 2015 "ИП БЫСТРОВ В.И."  Аренда недвижимости без посредников.
             <a href="{% url 'agreement' %}">Пользовательское соглашение.</a>
             <a href="http://vk.com/agnevo"><img height="24" src="{{ STATIC_URL }}images/social/VKontakte.png"/></a>
             <a href="http://ok.ru/group/52330037444829"><img height="24" src="{{ STATIC_URL }}images/social/Odnoklassniki.png"/></a>
        </p>
    </div>

    <script src="{{ STATIC_URL }}jquery/jquery-1.11.1.min.js"></script>
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>

    {% block script %}{% endblock %}

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56276017-1', 'auto');
      ga('send', 'pageview');

    </script>

</body>
</html>