agnevo/agnevo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from realty.views import SearchView, SubmitView, RealtyView, SubmitSuccessView, SubscribeView, \
    SubscribeDeleteView, RealtyFavouriteView, RevelationView, UserView, UserRealtyDeleteView, UserRealtyShowView, \
    UserRealtyHideView, UserRealtyFavouriteView
from accounts.views import LoginView, LogoutView, RegisterView, ResendView, \
    PayView, PayRobokassaSuccessView, PayRobokassaFailView, \
    PayRobokassaResultView, FeedbackView, FeedbackThanksView, AgreementView, OfferView, DiscountView


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AgNeVo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', SearchView.as_view(), name='search'),
    url(r'^submit/$', SubmitView.as_view(), name='submit'),
    url(r'^submit/success/$', SubmitSuccessView.as_view(), name='submit_success'),
    url(r'^realty/(?P<id>\d+)/$', RealtyView.as_view(), name='realty'),
    url(r'^feedback/$', FeedbackView.as_view(), name='feedback'),
    url(r'^feedback/thanks/$', FeedbackThanksView.as_view(), name='feedback_thanks'),
    url(r'^subscribe/$', SubscribeView.as_view(), name='subscribe'),
    url(r'^favourite/$', RealtyFavouriteView.as_view(), name='favourite'),
    url(r'^subscribe/delete/$', SubscribeDeleteView.as_view(), name='subscribe_delete'),
    url(r'^agreement/$', AgreementView.as_view(), name='agreement'),
    url(r'^offer/$', OfferView.as_view(), name='offer'),
    url(r'^discount/$', DiscountView.as_view(), name='discount'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^account/login/$', LoginView.as_view(), name='login'),
    url(r'^account/log_out/$', LogoutView.as_view(), name='logout'),
    url(r'^account/register/$', RegisterView.as_view(), name='register'),
    url(r'^account/resend/$', ResendView.as_view(), name='resend'),
    url(r'^account/revelation/$', RevelationView.as_view(), name='revelation'),
    url(r'^account/pay/$', PayView.as_view(), name='pay'),
    url(r'^account/pay/robokassa/success/$', PayRobokassaSuccessView.as_view(), name='pay_robokassa_success'),
    url(r'^account/pay/robokassa/fail/$', PayRobokassaFailView.as_view(), name='pay_robokassa_fail'),
    url(r'^account/pay/robokassa/result/$', csrf_exempt(PayRobokassaResultView.as_view()), name='pay_robokassa_result'),
    url(r'^account/user/$', UserView.as_view(), name='user'),
    url(r'^account/user/realty/(?P<pk>\d+)/delete/$', UserRealtyDeleteView.as_view(), name='user_realty_delete'),
    url(r'^account/user/realty/(?P<pk>\d+)/show/$', UserRealtyShowView.as_view(), name='user_realty_show'),
    url(r'^account/user/realty/(?P<pk>\d+)/hide/$', UserRealtyHideView.as_view(), name='user_realty_hide'),
    url(r'^account/user/realty/(?P<pk>\d+)/favourite/$', UserRealtyFavouriteView.as_view(), name='user_realty_favourite'),


    url(r'^api/account/login/$', csrf_exempt(LoginView.as_view())),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agnevo/realty/models.py
# -*- coding: utf-8 -*-
from django.db import models
from realty.tools import get_yandex_object


class Region(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class City(models.Model):
    region = models.ForeignKey('Region')
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.region.name + ' - ' + self.name


class District(models.Model):
    city = models.ForeignKey('City')
    name = models.CharField(max_length=100)

    def short_name(self):
        return self.name.split()[0]

    def __str__(self):
        return self.city.name + ' - ' + self.name


class Realty(models.Model):
    REALTY_KIND = [
        ('apartment_1', u'1 комнатная квартира'),
        ('apartment_2', u'2-х комнатная квартира'),
        ('apartment_3', u'3-х комнатная квартира'),
        ('apartment_4', u'4 и более комнат'),
        ('studio', u'квартира студия'),
        ('room', u'комната'),
        ('dormitory', u'общежитие'),
        ('homestead', u'частный дом'),
        ('homestead_part', u'часть дома'),
        ('bed', u'койко-место'),
        ('garage', u'гараж'),
        # ('shop', u'торговое помещение'),
        # ('office', u'офисное помещение'),
        # ('store', u'складское помещение'),
        # ('production', u'производственное помещение'),
    ]

    DURATION_TYPE = (
        ('long', 'длительный период'),
        ('daily', 'посуточно'),
    )

    ADVERTISEMENT_TYPE = (
        ('lease', 'Сдаю'),
        ('sell', 'Продаю'),
    )

    city = models.ForeignKey('City', verbose_name="город")
    district = models.ForeignKey('District', blank=True, null=True, verbose_name="район")
    sub_district = models.CharField(max_length=100, blank=True, null=True, verbose_name="поселок или микрорайон")
    street = models.CharField(max_length=100, verbose_name="улица")
    house = models.CharField(max_length=100, verbose_name="номер дома")
    lat = models.FloatField()
    lon = models.FloatField()

    price = models.PositiveIntegerField(verbose_name="цена")
    contact = models.CharField(max_length=100, verbose_name="контактный телефон")

    kind = models.CharField(max_length=100, choices=REALTY_KIND, verbose_name="тип")
    duration = models.CharField(max_length=100, choices=DURATION_TYPE, verbose_name="длительность")
    is_furniture = models.BooleanField(default=False, verbose_name="есть ли мебель")
    floor = models.PositiveIntegerField(verbose_name="этаж")
    storeys = models.PositiveIntegerField(verbose_name="количество этажей в доме")
    description = models.TextField(blank=True, verbose_name="описание")

    image1 = models.ImageField(blank=True, verbose_name="Изображение", upload_to='images', default=None, null=True)
    image2 = models.ImageField(blank=True, verbose_name="Изображение", upload_to='images', default=None, null=True)
    image3 = models.ImageField(blank=True, verbose_name="Изображение", upload_to='images', default=None, null=True)
    image4 = models.ImageField(blank=True, verbose_name="Изображение", upload_to='images', default=None, null=True)
    image5 = models.ImageField(blank=True, verbose_name="Изображение", upload_to='images', default=None, null=True)

    is_show = models.BooleanField(default=True, verbose_name="показать")
    is_publish = models.BooleanField(default=False, verbose_name="опубликовано")
    submit_date = models.DateTimeField()
    publish_date = models.DateTimeField(blank=True, null=True)
    check_date = models.DateTimeField(blank=True, null=True)

    user = models.ForeignKey('accounts.User', blank=True, null=True, related_name='+')

    def __str__(self):
        return self.city.name + ' - ' + self.street + ' ' + self.house

    def address(self):
        return self.street + ' ' + self.house

    def kind_display(self):
        for choise in self.REALTY_KIND:
            if self.kind == choise[0]:
                return choise[1]

    def is_furniture_display(self):
        if self.is_furniture:
            return 'да'
        return 'нет'

    def check_date_display(self):
        if self.check_date:
            return self.check_date
        return 'нет'

    def lat_display(self):
        return str(self.lat)

    def lon_display(self):
        return str(self.lon)

    def save(self, *args, **kwargs):
        if not self.lat and not self.lon:
            obj = get_yandex_object('Россия', self.city.region.name, self.city.name,
                                    self.street, self.house)
            if obj:
                self.lat = obj['lat']
                self.lon = obj['lon']

        super(Realty, self).save(*args, **kwargs)

        # if self.user.is_admin and self.is_publish and self.is_show:
        #     print('Send sms')
        #     delivery_realities_sms(self.id)

agnevo/realty/forms.py
from django import forms
from django.forms import Form, ModelForm
from django.forms import ModelChoiceField
from captcha.fields import CaptchaField
from realty.models import Realty, City, District


class BootstrapSelect(forms.Select):
    def __init__(self, attrs=None):
        result_attrs = {'class': 'form-control'}
        if attrs:
            result_attrs.update(attrs)
        super(BootstrapSelect, self).__init__(attrs=result_attrs)


class CityField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class DistrictField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj


class DistrictMultiField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

    def __instancecheck__(self, instance):
        if instance is forms.ModelMultipleChoiceField:
            return True


class SearchForm(Form):
    # KINDS = [('', 'тип...')] + Realty.REALTY_KIND
    KINDS = Realty.REALTY_KIND
    PRICES_FROM = (
        ('', 'цена от...'),
        ('3000', '3000'),
        ('5000', '5000'),
        ('7000', '7000'),
        ('10000', '10000'),
        ('12000', '12000'),
        ('15000', '15000'),
        ('20000', '20000'),
    )
    PRICES_TO = (
        ('', 'цена до...'),
        ('3000', '3000'),
        ('5000', '5000'),
        ('7000', '7000'),
        ('10000', '10000'),
        ('12000', '12000'),
        ('15000', '15000'),
        ('20000', '20000'),
    )
    FURNITURE = (
        ('', 'мебель...'),
        ('yes', 'с мебелью'),
        ('no', 'без мебели'),
    )
    DURATION = (
        ('', 'период...'),
        ('long', 'длительный'),
        ('daily', 'посуточно'),
    )

    city = CityField(queryset=City.objects, required=True, label=None, empty_label=None,
                     widget=forms.Select(attrs={'class': 'form-control'}))
    district = DistrictMultiField(queryset=District.objects, required=False)
    kind = forms.MultipleChoiceField(choices=KINDS, required=False)
    is_photo = forms.BooleanField(required=False, help_text='С фото')

    # city = CityField(queryset=City.objects, empty_label='город...', required=False, initial=1,
    #                  widget=forms.Select(attrs={'class': 'form-control'}))
    # district = DistrictField(queryset=District.objects, empty_label='район...', required=False,
    #                          widget=forms.Select(attrs={'class': 'form-control'}))
    # kind = forms.ChoiceField(choices=KINDS, required=False,
    #                          widget=forms.Select(attrs={'class': 'form-control'}))
    is_furniture = forms.ChoiceField(choices=FURNITURE, required=False,
                                     widget=forms.Select(attrs={'class': 'form-control'}))
    price_from = forms.ChoiceField(choices=PRICES_FROM, required=False,
                                   widget=forms.Select(attrs={'class': 'form-control'}))
    price_to = forms.ChoiceField(choices=PRICES_TO, required=False,
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    duration = forms.ChoiceField(choices=DURATION, required=False,
                                 widget=forms.Select(attrs={'class': 'form-control'}))


class SubmitForm(Form):
    city = CityField(queryset=City.objects.all(), empty_label=None,
                     widget=forms.Select(attrs={'class': 'form-control'}))
    district = DistrictField(queryset=District.objects, label='Район',
                             empty_label=None, required=False,
                             widget=forms.Select(attrs={'class': 'form-control'}))
    sub_district = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'необязательное поле'}))
    street = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    house = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    lat = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    lon = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control'}))

    duration = forms.ChoiceField(choices=Realty.DURATION_TYPE, widget=BootstrapSelect)
    price = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'за месяц или за сутки если посуточно'}))
    contact = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'телефон и имя'}))

    kind = forms.ChoiceField(choices=Realty.REALTY_KIND, widget=BootstrapSelect)

    is_furniture = forms.BooleanField(required=False)

    floor = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    storeys = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control'}))

    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}))

    image1 = forms.ImageField(required=False)
    image2 = forms.ImageField(required=False)
    image3 = forms.ImageField(required=False)
    image4 = forms.ImageField(required=False)
    image5 = forms.ImageField(required=False)

    captcha = CaptchaField(label='Введите текст с картинки')

agnevo/realty/templates/realty/contact.html
{% if realty.access_contact == 'no_auth' %}
    <a href="{% url 'login' %}">Показать телефон</a>
{% elif realty.access_contact == 'premium' %}
    {{ realty.contact }}
{% elif realty.access_contact == 'revelation' %}
    {{ realty.contact }} (по баллам)
{% elif realty.access_contact == 'points' %}
    <a href="#" onclick="SubmitForm('revelation_{{ realty.id }}')">Показать телефон (потратить балл)</a>
    <form id="revelation_{{ realty.id }}" method="post" action={% url 'revelation' %}>
    {% csrf_token %}
    <input type='hidden' name='return_path' value='{{ cur_path }}' />
    <input type='hidden' name='realty_id' value='{{ realty.id }}' />
    </form>
{% else %}
    <a href="{% url 'pay' %}">Получить доступ</a>
{% endif %}

agnevo/realty/templates/realty/search.html
{% extends "base.html" %}

{% block link %}
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap-multiselect.css" type="text/css"/>
{% endblock %}

{% block custom_content %}

{% if not user.is_authenticated %}
    <div class="alert alert-info" role="alert">
        Для просмотра контактов собственника и подключения услуги СМС подписка необходимо <a href="{% url 'register' %}" class="alert-link">зарегистрироваться</a>
    </div>
{% endif %}

    <form action="{% url 'search' %}" method="post" role="form" class="form-inline">
        {% csrf_token %}
                {% if False %}{{ form.city }}{% endif %}
                {{ form.city }}
                {{ form.district }}
                {{ form.kind }}
                {{ form.is_furniture }}
                {{ form.price_from }}
                {{ form.price_to }}
                {{ form.duration }}
        <button type="submit" name="search" class="btn btn-success">Поиск</button>
        {% if user.is_authenticated %}
            {% if is_favourite %}
                <a href="{% url 'favourite' %}" class="btn btn-primary active">Показать все</a>
            {% else %}
                <a href="{% url 'favourite' %}" class="btn btn-primary">Показать избранное</a>
            {% endif %}
        {% endif %}
        <br>{{ form.is_photo }} Только с фото
    </form>

    <div class="table-responsive">
        <table class="table table-striped">
        <thead>
            <tr class="table-head">
                <th>Проверено</th>
                <th>Район</th>
                <th>Адрес</th>
                <th>Тип</th>
                <th>Мебель</th>
                <th>Цена</th>
                <th>Контакты</th>
                {% if user.is_authenticated %}
                <th><span class="glyphicon glyphicon-th"></span></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for realty in realties %}
            <tr class="table-content">
                <td><a class="link-content" href="{% url 'realty' realty.id %}">{{ realty.check_date|date:"d N Y" }}</a></td>
                <td><a class="link-content" href="{% url 'realty' realty.id %}">{{ realty.district.short_name }}</a></td>
                <td><a class="link-content" href="{% url 'realty' realty.id %}">{{ realty.sub_district }} {{ realty.address }}</a></td>
                <td>{{ realty.kind_display }}</td>
                <td>{{ realty.is_furniture|yesno:"Да,Нет," }}</td>
                <td>{{ realty.price }}{% if realty.duration == 'long' %} в мес.{% else %} в сут.{% endif %}</td>
                <td>{% include "realty/contact.html" %}</td>
            {% if user.is_authenticated %}
                {% if not realty.is_favourite %}
                    <td><a href="{% url 'user_realty_favourite' realty.id %}" title="Добавить в избранное"><span class="glyphicon glyphicon-star-empty"></span></a></td>
                {% else %}
                    <td><a href="{% url 'user_realty_favourite' realty.id %}" title="Убрать из избранного"><span class="glyphicon glyphicon-star"></span></a></td>
                {% endif %}
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>

    {% if is_paginated %}
    <ul class="pagination">
        <li><a href="?page=1">&laquo;</a></li>
        {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
                <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
            {%  else %}
                <li><a href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        <li><a href="?page={{ paginator.num_pages }}">&raquo;</a></li>
    </ul>
    {% endif %}

{% endblock %}

{% block script %}
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap-multiselect.js"></script>

    <script type="text/javascript">
    $(document).ready(function() {
        $('#id_district').multiselect({
            numberDisplayed: 2,
            nonSelectedText: "районы...",
            includeSelectAllOption: true,
            selectAllText: 'Все районы',
            nSelectedText: 'Выбрано: ',

            buttonText: function(options, select) {
                if (options.length == 0) {
                    return this.nonSelectedText + ' <b class="caret"></b>';
                }
                else {
                    if (options.length > this.numberDisplayed) {
                        return this.nSelectedText + ' ' + options.length + ' <b class="caret"></b>';
                    }
                    else {
                        var selected = '';
                        options.each(function() {
                            var label = ($(this).attr('label') !== undefined) ? $(this).attr('label') : $(this).html();
                            selected += label + ', ';
                        });
                        return selected.substr(0, selected.length - 2) + ' <b class="caret"></b>';
                    }
                }
            }
        });
    });

    $(document).ready(function() {
        $('#id_kind').multiselect({
            numberDisplayed: 2,
            nonSelectedText: "тип...",
            includeSelectAllOption: true,
            selectAllText: 'Все типы',
            nSelectedText: 'Выбрано вариантов: ',

            buttonText: function(options, select) {
                if (options.length == 0) {
                    return this.nonSelectedText + ' <b class="caret"></b>';
                }
                else {
                    if (options.length > this.numberDisplayed) {
                        return this.nSelectedText + ' ' + options.length + ' <b class="caret"></b>';
                    }
                    else {
                        var selected = '';
                        options.each(function() {
                            var label = ($(this).attr('label') !== undefined) ? $(this).attr('label') : $(this).html();
                            selected += label + ', ';
                        });
                        return selected.substr(0, selected.length - 2) + ' <b class="caret"></b>';
                    }
                }
            }
        });
    });
    </script>

    <script type="text/javascript">
        $(document).ready(function() {
            function modify_district() {
                var city = $('#id_city');
                var district = $('#id_district');
                var district_data = {{ district_data|safe }};
                district.empty().append(district_data[city.val()]);
                district.multiselect('rebuild');

                if (district_data[city.val()]) {
                    district.multiselect('enable');
                } else {
                    district.multiselect('disable');
                }
            }

            $("#id_city").change(modify_district);
            modify_district();
        });
    </script>
{% endblock %}

agnevo/realty/templates/realty/submit.html
{% extends "base.html" %}

{% block content %}

<div class="well">
<h3>УВАЖАЕМЫЕ СОБСТВЕННИКИ ЖИЛЬЯ!</h3>
Заполните приведенную ниже форму чтобы сдать квартиру или прочие объекты недвижимости. После  проверки  оператором ваше объявление появится в разделе "Поиск".  Представителям агентств недвижимости или частным риелторам – просьба не утруждаться!
</div>

{% if user.is_authenticated %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">Ошибка заполнения формы, проверьте правильность заполнения всех полей и повторите попытку</div>
{% endif %}

<form enctype="multipart/form-data" action="{% url 'submit' %}" method="post" role="form" class="form-horizontal">
    {% csrf_token %}

    {% if form.city.errors %}
    <div class="alert alert-danger" role="alert">{{ form.city.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_city" class="col-sm-2 control-label">Город</label>
        <div class="col-sm-6">
        {{ form.city }}
        </div>
    </div>

    {% if form.district.errors %}
    <div class="alert alert-danger" role="alert">{{ form.district.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_district" class="col-sm-2 control-label">Район</label>
        <div class="col-sm-6">
        {{ form.district }}
        </div>
    </div>

    {% if form.sub_district.errors %}
    <div class="alert alert-danger" role="alert">{{ form.sub_district.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_sub_district" class="col-sm-2 control-label">Поселок или микрорайон</label>
        <div class="col-sm-6">
        {{ form.sub_district }}
        </div>
    </div>

    {% if form.street.errors %}
    <div class="alert alert-danger" role="alert">{{ form.street.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_street" class="col-sm-2 control-label">Улица</label>
        <div class="col-sm-6">
        {{ form.street }}
        </div>
    </div>

    {% if form.house.errors %}
    <div class="alert alert-danger" role="alert">{{ form.house.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_house" class="col-sm-2 control-label">Дом</label>
        <div class="col-sm-6">
        {{ form.house }}
        </div>
    </div>

    {% if form.duration.errors %}
    <div class="alert alert-danger" role="alert">{{ form.duration.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Длительность</label>
        <div class="col-sm-6">
        {{ form.duration }}
        </div>
    </div>

    {% if form.price.errors %}
    <div class="alert alert-danger" role="alert">{{ form.price.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_price" class="col-sm-2 control-label">Цена</label>
        <div class="col-sm-6">
        {{ form.price }}
        </div>
    </div>

    {% if form.contact.errors %}
    <div class="alert alert-danger" role="alert">{{ form.contact.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Контакты</label>
        <div class="col-sm-6">
        {{ form.contact }}
        </div>
    </div>

    {% if form.kind.errors %}
    <div class="alert alert-danger" role="alert">{{ form.kind.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Тип</label>
        <div class="col-sm-6">
        {{ form.kind }}
        </div>
    </div>

    {% if form.is_furniture.errors %}
    <div class="alert alert-danger" role="alert">{{ form.is_furniture.errors }}</div>
    {% endif %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
                <div class="checkbox">
                <label>
                    {{ form.is_furniture }} Есть ли мебель
                </label>
            </div>
        </div>
    </div>

    {% if form.floor.errors %}
    <div class="alert alert-danger" role="alert">{{ form.floor.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Этаж</label>
        <div class="col-sm-2">
        {{ form.floor }}
        </div>
        <label for="id_contact" class="col-sm-2 control-label">Всего этажей</label>
        <div class="col-sm-2">
        {{ form.storeys }}
        </div>

    </div>

    {% if form.description.errors %}
    <div class="alert alert-danger" role="alert">{{ form.description.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Описание</label>
        <div class="col-sm-6">
        {{ form.description }}
        </div>
    </div>

    {% if form.image1.errors %}
    <div class="alert alert-danger" role="alert">{{ form.image1.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Изображение</label>
        <div class="col-sm-6">
        {{ form.image1 }}
        </div>
    </div>

    {% if form.image2.errors %}
    <div class="alert alert-danger" role="alert">{{ form.image2.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Изображение</label>
        <div class="col-sm-6">
        {{ form.image2 }}
        </div>
    </div>

    {% if form.image3.errors %}
    <div class="alert alert-danger" role="alert">{{ form.image3.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_contact" class="col-sm-2 control-label">Изображение</label>
        <div class="col-sm-6">
        {{ form.image3 }}
        </div>
    </div>


    {% if form.captcha.errors %}
    <div class="alert alert-danger" role="alert">{{ form.captcha.errors }}</div>
    {% endif %}
    <div class="form-group">
        <label for="id_captcha_1" class="col-sm-2 control-label">Текст с картинки</label>
        <div class="input-group col-sm-6">
            {{ form.captcha }}
        </div>
    </div>

    <input type="hidden" value="0" name="lon">
    <input type="hidden" value="0" name="lat">

    <br>

    <button type="submit" class="btn btn-default">Отправить на рассмотрение</button>
</form>

{% else %}
    <div class="alert alert-info" role="alert">
        Вы должны <a href="{% url 'register' %}" class="alert-link">зарегистрироваться</a>, чтобы подать объявление
    </div>
{% endif %}

<br>
{% endblock %}

{% block script %}
<script type="text/javascript">

    function modify_district() {
        var city = $('#id_city');
        var district = $('#id_district');
        var district_data = {{ district_data|safe }};
        district.empty().append(district_data[city.val()]);
    }

    $( "#id_city" ).change(modify_district);
    modify_district();

</script>
{% endblock %}

agnevo/realty/templates/realty/submit_success.html
{% extends "base.html" %}

{% block content %}
<div class="well">Ваша заявка принята, после проверки модератором она появится в списке объявлений</div>
<p><a href="{% url 'submit' %}" class="btn btn-default">Подать еще объявление</a></p>
{% endblock %}

agnevo/realty/templates/realty/subscribe_delete.html
{% extends "base.html" %}

{% block content %}
<div class="well">Подписка на СМС отменена. Изменить или удалить подписку можно в личном кабинете</div>
{% endblock %}

agnevo/realty/templates/realty/user_realty_delete.html
{% extends "base.html" %}

{% block content %}
<div class="alert alert-warning" role="alert">
    Удалить объявление "{{ object.city.name }}, {{ object.street }} {{ object.house }}"?
</div>
<form action="" method="post" role="form">{% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a class="btn btn-default" href="{% url 'user' %}">Отмена</a>
</form>
{% endblock %}